const Complaint = require("../models/Complaint");
const Ward = require("../models/Ward");
const { calculateSlaDeadline } = require("../services/slaService");
const socketService = require("../services/socketService");
const { BMC_WARDS_DATA } = require("../scripts/seedWardBoundaries");

// Helper for Point-in-Polygon
function isPointInPolygon(point, polygonCoordinates) {
  const [lng, lat] = point;
  let inside = false;
  for (let i = 0, j = polygonCoordinates.length - 1; i < polygonCoordinates.length; j = i++) {
    const xi = polygonCoordinates[i][0], yi = polygonCoordinates[i][1];
    const xj = polygonCoordinates[j][0], yj = polygonCoordinates[j][1];
    const intersect = yi > lat !== yj > lat && lng < ((xj - xi) * (lat - yi)) / (yj - yi) + xi;
    if (intersect) inside = !inside;
  }
  return inside;
}

/**
 * ─── IoT Smart City Telemetry Ingestion Controller ────────────────────────────
 * @route   POST /api/iot/telemetry
 * @access  Public (IoT Gateway / API Token)
 */
const ingestTelemetry = async (req, res) => {
  try {
    const { deviceId, sensorType, value, lat, lng, ward } = req.body;

    if (!deviceId || !sensorType || value === undefined) {
      return res.status(400).json({
        success: false,
        message: "deviceId, sensorType, and value are required for IoT telemetry ingestion.",
      });
    }

    let shouldCreateTicket = false;
    let title = "";
    let description = "";
    let category = "general";
    let departmentId = "GEN";
    let severity = "medium";

    const numValue = Number(value);

    // ── Evaluate IoT Sensor Thresholds ──
    if (sensorType === "ultrasonic_fill") {
      if (numValue >= 85) {
        shouldCreateTicket = true;
        title = `[IoT Auto-Alert] Dumpster Overfill (${numValue}% Capacity) at ${deviceId}`;
        description = `Smart City Ultrasonic Fill Sensor on unit ${deviceId} detected trash volume at ${numValue}%, exceeding 85% municipal overflow threshold. Automated SWM collection required.`;
        category = "garbage_collection";
        departmentId = "SWM";
        severity = numValue >= 95 ? "critical" : "high";
      }
    } else if (sensorType === "water_pressure") {
      if (numValue <= 15) {
        shouldCreateTicket = true;
        title = `[IoT Auto-Alert] Pipeline Burst / Low Pressure (${numValue} PSI) at ${deviceId}`;
        description = `Sub-surface pressure transducer ${deviceId} detected severe drop to ${numValue} PSI (Normal: 45-60 PSI). Immediate municipal pipeline rupture inspection required.`;
        category = "water_and_sanitation";
        departmentId = "WSD";
        severity = "critical";
      }
    } else if (sensorType === "voltage_fault") {
      if (numValue === 0) {
        shouldCreateTicket = true;
        title = `[IoT Auto-Alert] Feeder Pillar Outage at ${deviceId}`;
        description = `Smart lighting telemetry node ${deviceId} detected 0V line current across street fixture circuit.`;
        category = "street_lighting";
        departmentId = "ELD";
        severity = "medium";
      }
    }

    if (!shouldCreateTicket) {
      return res.status(200).json({
        success: true,
        message: `Telemetry received. Value ${numValue} is within normal operating limits for ${sensorType}. No ticket created.`,
        sensorStatus: "NOMINAL",
      });
    }

    // Resolve Ward
    const targetLat = Number(lat) || 19.0596;
    const targetLng = Number(lng) || 72.8295;
    let resolvedWardName = ward || "Ward H-West";
    let resolvedWardCode = "H-W";

    for (const w of BMC_WARDS_DATA) {
      if (isPointInPolygon([targetLng, targetLat], w.boundary.coordinates[0])) {
        resolvedWardName = w.wardName;
        resolvedWardCode = w.wardCode;
        break;
      }
    }

    const randomSuffix = Math.floor(1000 + Math.random() * 9000);
    const complaintId = `BMC-2026-IOT-${randomSuffix}`;
    const slaDeadline = calculateSlaDeadline(severity);

    const complaint = await Complaint.create({
      complaintId,
      title,
      description,
      category,
      departmentId,
      department: departmentId,
      severity,
      wardName: resolvedWardName,
      wardCode: resolvedWardCode,
      ward: resolvedWardName,
      slaDeadline,
      slaStatus: "on_time",
      escalationTier: 1,
      location: {
        type: "Point",
        coordinates: {
          type: "Point",
          coordinates: [targetLng, targetLat],
        },
        address: `Smart Sensor Node ${deviceId}, ${resolvedWardName}, Mumbai`,
        ward: resolvedWardName,
      },
      status: "ai_verified",
      statusHistory: [
        {
          status: "submitted",
          note: `Auto-generated by Municipal IoT Telemetry Gateway (Device: ${deviceId}, Type: ${sensorType}, Value: ${numValue}).`,
        },
        {
          status: "ai_verified",
          note: `Threshold breach verified. Auto-routed to ${departmentId} department in ${resolvedWardName}.`,
        },
      ],
      aiVerification: {
        isVerified: true,
        detectedCategory: category,
        confidence: 0.98,
        severity,
        notes: `IoT Rule Engine: Automatic threshold trip on ${sensorType}`,
        source: "IOT_TELEMETRY_ENGINE",
      },
    });

    // Broadcast Real-Time Alert
    try {
      socketService.broadcastComplaintCreated({
        complaintId: complaint.complaintId || complaint._id,
        title: complaint.title,
        ward: complaint.wardName,
        category: complaint.category,
        priority: complaint.severity,
      });
    } catch (sErr) {
      console.warn("Socket broadcast warning:", sErr.message);
    }

    return res.status(201).json({
      success: true,
      message: "IoT Telemetry breach confirmed. Municipal action ticket created.",
      complaintId: complaint.complaintId || complaint._id,
      title: complaint.title,
      department: complaint.departmentId,
      ward: complaint.wardName,
      severity: complaint.severity,
      slaDeadline: complaint.slaDeadline,
      trackingUrl: `/complaint/${complaint.complaintId || complaint._id}/track`,
    });
  } catch (error) {
    console.error("IoT Ingestion Error:", error.message);
    return res.status(500).json({ success: false, message: "Server error ingesting IoT telemetry." });
  }
};

module.exports = {
  ingestTelemetry,
};
